import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const figtree = Figtree({
  subsets: ["latin"], // Optimize for Latin characters
  weight: ["400", "700"], // Load specific font weights
  variable: "--font-figtree", // Define a CSS variable
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${figtree.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
